# Generated by Django 3.2 on 2021-04-22 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files_from_user', '0002_alter_image_to_eval_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image_to_eval',
            name='date_up',
        ),
        migrations.RemoveField(
            model_name='image_to_eval',
            name='user',
        ),
    ]
