# Generated by Django 3.2 on 2021-04-22 22:58

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import files_from_user.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('files_from_user', '0004_auto_20210422_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image_to_eval',
            name='file',
            field=models.FileField(upload_to=files_from_user.models.custom_dir, validators=[django.core.validators.FileExtensionValidator(['JPEG', 'PNG', 'GIF', 'JPG', 'TIFF', 'EPS', 'RAW'], "Please upload an image with one of     the following extensions 'JPEG', 'PNG', 'GIF', 'JPG', 'TIFF', 'EPS', 'RAW'")], verbose_name='Upload'),
        ),
        migrations.AlterField(
            model_name='image_to_eval',
            name='user',
            field=models.ForeignKey(default=None, help_text='User That uploaded file.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
