# Generated by Django 3.2 on 2021-04-22 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files_from_user', '0007_image_to_eval_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image_to_eval',
            options={},
        ),
        migrations.RemoveField(
            model_name='image_to_eval',
            name='date_up',
        ),
        migrations.RemoveField(
            model_name='image_to_eval',
            name='file',
        ),
        migrations.RemoveField(
            model_name='image_to_eval',
            name='is_auth',
        ),
        migrations.RemoveField(
            model_name='image_to_eval',
            name='user',
        ),
    ]
