# Generated by Django 3.2 on 2021-04-22 23:24

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import files_from_user.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('files_from_user', '0008_auto_20210422_2303'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image_to_eval',
            options={'verbose_name': 'File', 'verbose_name_plural': 'Files'},
        ),
        migrations.AddField(
            model_name='image_to_eval',
            name='date_up',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='when was uploaded'),
        ),
        migrations.AddField(
            model_name='image_to_eval',
            name='file',
            field=models.FileField(default='settings.MEDIA_ROOT/default/home', upload_to=files_from_user.models.custom_dir, validators=[django.core.validators.FileExtensionValidator(['JPEG', 'PNG', 'GIF', 'JPG', 'TIFF', 'EPS', 'RAW'], "Please upload an image with one of     the following extensions 'JPEG', 'PNG', 'GIF', 'JPG', 'TIFF', 'EPS', 'RAW'")], verbose_name='Upload'),
        ),
        migrations.AddField(
            model_name='image_to_eval',
            name='is_auth',
            field=models.BooleanField(default=False, help_text='True if the user is part of our community i.e registered.', verbose_name='User Is Authenticated'),
        ),
        migrations.AddField(
            model_name='image_to_eval',
            name='user',
            field=models.ForeignKey(blank=True, default=None, help_text='User That uploaded file.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
