# Generated by Django 3.2 on 2021-04-10 12:57

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_birthday',
            field=models.DateTimeField(verbose_name='Date Of Birth'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=150, validators=[django.core.validators.RegexValidator(code='invalid', flags=re.RegexFlag['IGNORECASE'], message='Wrong Name, Try Again.[Max Length: 150 characters, Must Have At Least 2 characters.]', regex='^[a-z][a-z]+$')], verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=150, validators=[django.core.validators.RegexValidator(code='invalid', flags=re.RegexFlag['IGNORECASE'], message='Wrong Name, Try Again.[Max Length: 150 characters, Must Have At Least 2 characters.]', regex='^[a-z][a-z]+$')], verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=40, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_username', flags=re.RegexFlag['IGNORECASE'], message='Wrong Username, Try Again.[Max Length: 40 characters, Must Start With: 4 Characters, Allowed: Alphanumeric, Underscore]', regex='^[a-z]\\w+')], verbose_name='Username'),
        ),
    ]
